# Use the official .NET 9 SDK Windows ARM64 image as the base image
FROM mcr.microsoft.com/dotnet/sdk:9.0-windowsservercore-ltsc2022-arm64

# Set the working directory
WORKDIR /app

# Default command to keep the container alive
CMD ["cmd"]
