name: Build and Test on Linux ARM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build -c Release tests/GrindCore.Tests/GrindCore.Tests.csproj -r linux-arm -p:TargetFramework=net8.0 -p:TargetFrameworks=net8.0

    - name: Set up Docker Buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name mybuilder

    - name: Build Docker image
      run: docker buildx build --platform linux/arm/v7 -t linux-arm -f .github/workflows/Dockerfile.linux-arm . --load

    - name: Run tests in Docker container
      run: docker run -it --rm --platform linux/arm/v7 -v "$(pwd):/app" linux-arm /app/tests/GrindCore.Tests.Runtime/bin/Release/net8.0/linux-arm/GrindCore.Tests.Runtime