name: Run Unit Tests

on:
  push:
    branches:
      - main
      - test/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_all_platforms:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build project for all platforms
        run: |
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r linux-arm64 -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/linux-arm64
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r linux-arm -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/linux-arm
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r linux-x64 -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/linux-x64
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r osx-x64 -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/osx-x64
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r osx-arm64 -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/osx-arm64
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r win-x64 -p:TargetFramework=net9.0 -p:TargetFrameworks=net9.0 -o output/win-x64
          dotnet publish tests/GrindCore.Tests/GrindCore.Tests.csproj -c Debug -r win-x86 -p:RuntimeIdentifier=win-x86 -p:TargetFramework=net9.0 -o output/win-x86

      - name: Archive build outputs
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: output/
